alias: "Uplights: Holiday Scene Manager (Final Hardened)"
description: >-
  Applies specific effects based on date. Includes double-tap speed enforcement
  for UDP reliability. Valentine's Day (Feb 13-16), NYE Party, Fireplace default.
triggers:
  - trigger: state
    entity_id:
      - light.uplight1
      - light.uplight2
      - light.uplight3
      - light.uplight4
    to: "on"
    from:
      - unavailable
      - "off"
    for: "00:00:05"
  - trigger: time_pattern
    minutes: /15
conditions:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: or
    conditions:
      - condition: state
        entity_id: light.uplight1
        state: "on"
      - condition: state
        entity_id: light.uplight2
        state: "on"
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ now().month == 12 and now().day == 31 }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id:
                - light.uplight1
                - light.uplight2
                - light.uplight3
                - light.uplight4
            data:
              effect: Party
              brightness: 255
          - action: number.set_value
            target:
              entity_id:
                - number.uplight1_effect_speed
                - number.uplight2_effect_speed
                - number.uplight3_effect_speed
                - number.uplight4_effect_speed
            data:
              value: 100
      - conditions:
          - condition: template
            value_template: "{{ now().month == 2 and now().day >= 13 and now().day <= 16 }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id:
                - light.uplight1
                - light.uplight2
                - light.uplight3
                - light.uplight4
            data:
              effect: Valentine
              brightness: 255
          - delay: "00:00:02"
          - action: number.set_value
            target:
              entity_id:
                - number.uplight1_effect_speed
                - number.uplight2_effect_speed
                - number.uplight3_effect_speed
                - number.uplight4_effect_speed
            data:
              value: 20
    default:
      - action: light.turn_on
        target:
          entity_id:
            - light.uplight1
            - light.uplight2
            - light.uplight3
            - light.uplight4
        data:
          effect: Fireplace
          brightness: 200
      - delay: "00:00:02"
      - action: number.set_value
        target:
          entity_id:
            - number.uplight1_effect_speed
            - number.uplight2_effect_speed
            - number.uplight3_effect_speed
            - number.uplight4_effect_speed
        data:
          value: 50
mode: restart
