alias: "Uplights: Holiday Scene Manager (Final Hardened)"
description: >-
  Applies specific effects based on date. Includes double-tap speed enforcement
  for UDP reliability. Valentine Max (Feb 14-15), Fireplace default.
triggers:
  - trigger: state
    entity_id:
      - light.uplight1
      - light.uplight2
      - light.uplight3
      - light.uplight4
    to: "on"
    from:
      - unavailable
      - "off"
    for: "00:00:05"
  - trigger: time_pattern
    minutes: /15
conditions:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: or
    conditions:
      - condition: state
        entity_id: light.uplight1
        state: "on"
      - condition: state
        entity_id: light.uplight2
        state: "on"
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ now().month == 2 and now().day >= 14 and now().day <= 15 }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id:
                - light.wiz_par38
            data:
              transition: 1
              brightness_pct: 80
              rgb_color: [255, 0, 0]
    default:
      - action: light.turn_on
        target:
          entity_id:
            - light.uplight1
            - light.uplight2
            - light.uplight3
            - light.uplight4
        data:
          effect: Fireplace
          brightness: 200
      - delay: "00:00:02"
      - action: number.set_value
        target:
          entity_id:
            - number.uplight1_effect_speed
            - number.uplight2_effect_speed
            - number.uplight3_effect_speed
            - number.uplight4_effect_speed
        data:
          value: 50
mode: restart
